// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/redeemed2011/webflowAPI"
	"sync"
)

var (
	lockInterfaceMockGetAllCollections             sync.RWMutex
	lockInterfaceMockGetAllItemsInCollectionByID   sync.RWMutex
	lockInterfaceMockGetAllItemsInCollectionByName sync.RWMutex
	lockInterfaceMockGetCollectionByName           sync.RWMutex
	lockInterfaceMockMethodGet                     sync.RWMutex
)

// InterfaceMock is a mock implementation of Interface.
//
//     func TestSomethingThatUsesInterface(t *testing.T) {
//
//         // make and configure a mocked Interface
//         mockedInterface := &InterfaceMock{
//             GetAllCollectionsFunc: func() (*webflowAPI.Collections, error) {
// 	               panic("mock out the GetAllCollections method")
//             },
//             GetAllItemsInCollectionByIDFunc: func(collectionID string, maxPages int, myFunc webflowAPI.CollectFunc) error {
// 	               panic("mock out the GetAllItemsInCollectionByID method")
//             },
//             GetAllItemsInCollectionByNameFunc: func(collectionName string, maxPages int, myFunc webflowAPI.CollectFunc) error {
// 	               panic("mock out the GetAllItemsInCollectionByName method")
//             },
//             GetCollectionByNameFunc: func(name string) (*webflowAPI.Collection, error) {
// 	               panic("mock out the GetCollectionByName method")
//             },
//             MethodGetFunc: func(uri string, queryParams map[string]string, decodedResponse interface{}) error {
// 	               panic("mock out the MethodGet method")
//             },
//         }
//
//         // use mockedInterface in code that requires Interface
//         // and then make assertions.
//
//     }
type InterfaceMock struct {
	// GetAllCollectionsFunc mocks the GetAllCollections method.
	GetAllCollectionsFunc func() (*webflowAPI.Collections, error)

	// GetAllItemsInCollectionByIDFunc mocks the GetAllItemsInCollectionByID method.
	GetAllItemsInCollectionByIDFunc func(collectionID string, maxPages int, myFunc webflowAPI.CollectFunc) error

	// GetAllItemsInCollectionByNameFunc mocks the GetAllItemsInCollectionByName method.
	GetAllItemsInCollectionByNameFunc func(collectionName string, maxPages int, myFunc webflowAPI.CollectFunc) error

	// GetCollectionByNameFunc mocks the GetCollectionByName method.
	GetCollectionByNameFunc func(name string) (*webflowAPI.Collection, error)

	// MethodGetFunc mocks the MethodGet method.
	MethodGetFunc func(uri string, queryParams map[string]string, decodedResponse interface{}) error

	// calls tracks calls to the methods.
	calls struct {
		// GetAllCollections holds details about calls to the GetAllCollections method.
		GetAllCollections []struct {
		}
		// GetAllItemsInCollectionByID holds details about calls to the GetAllItemsInCollectionByID method.
		GetAllItemsInCollectionByID []struct {
			// CollectionID is the collectionID argument value.
			CollectionID string
			// MaxPages is the maxPages argument value.
			MaxPages int
			// MyFunc is the myFunc argument value.
			MyFunc webflowAPI.CollectFunc
		}
		// GetAllItemsInCollectionByName holds details about calls to the GetAllItemsInCollectionByName method.
		GetAllItemsInCollectionByName []struct {
			// CollectionName is the collectionName argument value.
			CollectionName string
			// MaxPages is the maxPages argument value.
			MaxPages int
			// MyFunc is the myFunc argument value.
			MyFunc webflowAPI.CollectFunc
		}
		// GetCollectionByName holds details about calls to the GetCollectionByName method.
		GetCollectionByName []struct {
			// Name is the name argument value.
			Name string
		}
		// MethodGet holds details about calls to the MethodGet method.
		MethodGet []struct {
			// URI is the uri argument value.
			URI string
			// QueryParams is the queryParams argument value.
			QueryParams map[string]string
			// DecodedResponse is the decodedResponse argument value.
			DecodedResponse interface{}
		}
	}
}

// GetAllCollections calls GetAllCollectionsFunc.
func (mock *InterfaceMock) GetAllCollections() (*webflowAPI.Collections, error) {
	if mock.GetAllCollectionsFunc == nil {
		panic("InterfaceMock.GetAllCollectionsFunc: method is nil but Interface.GetAllCollections was just called")
	}
	callInfo := struct {
	}{}
	lockInterfaceMockGetAllCollections.Lock()
	mock.calls.GetAllCollections = append(mock.calls.GetAllCollections, callInfo)
	lockInterfaceMockGetAllCollections.Unlock()
	return mock.GetAllCollectionsFunc()
}

// GetAllCollectionsCalls gets all the calls that were made to GetAllCollections.
// Check the length with:
//     len(mockedInterface.GetAllCollectionsCalls())
func (mock *InterfaceMock) GetAllCollectionsCalls() []struct {
} {
	var calls []struct {
	}
	lockInterfaceMockGetAllCollections.RLock()
	calls = mock.calls.GetAllCollections
	lockInterfaceMockGetAllCollections.RUnlock()
	return calls
}

// GetAllItemsInCollectionByID calls GetAllItemsInCollectionByIDFunc.
func (mock *InterfaceMock) GetAllItemsInCollectionByID(collectionID string, maxPages int, myFunc webflowAPI.CollectFunc) error {
	if mock.GetAllItemsInCollectionByIDFunc == nil {
		panic("InterfaceMock.GetAllItemsInCollectionByIDFunc: method is nil but Interface.GetAllItemsInCollectionByID was just called")
	}
	callInfo := struct {
		CollectionID string
		MaxPages     int
		MyFunc       webflowAPI.CollectFunc
	}{
		CollectionID: collectionID,
		MaxPages:     maxPages,
		MyFunc:       myFunc,
	}
	lockInterfaceMockGetAllItemsInCollectionByID.Lock()
	mock.calls.GetAllItemsInCollectionByID = append(mock.calls.GetAllItemsInCollectionByID, callInfo)
	lockInterfaceMockGetAllItemsInCollectionByID.Unlock()
	return mock.GetAllItemsInCollectionByIDFunc(collectionID, maxPages, myFunc)
}

// GetAllItemsInCollectionByIDCalls gets all the calls that were made to GetAllItemsInCollectionByID.
// Check the length with:
//     len(mockedInterface.GetAllItemsInCollectionByIDCalls())
func (mock *InterfaceMock) GetAllItemsInCollectionByIDCalls() []struct {
	CollectionID string
	MaxPages     int
	MyFunc       webflowAPI.CollectFunc
} {
	var calls []struct {
		CollectionID string
		MaxPages     int
		MyFunc       webflowAPI.CollectFunc
	}
	lockInterfaceMockGetAllItemsInCollectionByID.RLock()
	calls = mock.calls.GetAllItemsInCollectionByID
	lockInterfaceMockGetAllItemsInCollectionByID.RUnlock()
	return calls
}

// GetAllItemsInCollectionByName calls GetAllItemsInCollectionByNameFunc.
func (mock *InterfaceMock) GetAllItemsInCollectionByName(collectionName string, maxPages int, myFunc webflowAPI.CollectFunc) error {
	if mock.GetAllItemsInCollectionByNameFunc == nil {
		panic("InterfaceMock.GetAllItemsInCollectionByNameFunc: method is nil but Interface.GetAllItemsInCollectionByName was just called")
	}
	callInfo := struct {
		CollectionName string
		MaxPages       int
		MyFunc         webflowAPI.CollectFunc
	}{
		CollectionName: collectionName,
		MaxPages:       maxPages,
		MyFunc:         myFunc,
	}
	lockInterfaceMockGetAllItemsInCollectionByName.Lock()
	mock.calls.GetAllItemsInCollectionByName = append(mock.calls.GetAllItemsInCollectionByName, callInfo)
	lockInterfaceMockGetAllItemsInCollectionByName.Unlock()
	return mock.GetAllItemsInCollectionByNameFunc(collectionName, maxPages, myFunc)
}

// GetAllItemsInCollectionByNameCalls gets all the calls that were made to GetAllItemsInCollectionByName.
// Check the length with:
//     len(mockedInterface.GetAllItemsInCollectionByNameCalls())
func (mock *InterfaceMock) GetAllItemsInCollectionByNameCalls() []struct {
	CollectionName string
	MaxPages       int
	MyFunc         webflowAPI.CollectFunc
} {
	var calls []struct {
		CollectionName string
		MaxPages       int
		MyFunc         webflowAPI.CollectFunc
	}
	lockInterfaceMockGetAllItemsInCollectionByName.RLock()
	calls = mock.calls.GetAllItemsInCollectionByName
	lockInterfaceMockGetAllItemsInCollectionByName.RUnlock()
	return calls
}

// GetCollectionByName calls GetCollectionByNameFunc.
func (mock *InterfaceMock) GetCollectionByName(name string) (*webflowAPI.Collection, error) {
	if mock.GetCollectionByNameFunc == nil {
		panic("InterfaceMock.GetCollectionByNameFunc: method is nil but Interface.GetCollectionByName was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	lockInterfaceMockGetCollectionByName.Lock()
	mock.calls.GetCollectionByName = append(mock.calls.GetCollectionByName, callInfo)
	lockInterfaceMockGetCollectionByName.Unlock()
	return mock.GetCollectionByNameFunc(name)
}

// GetCollectionByNameCalls gets all the calls that were made to GetCollectionByName.
// Check the length with:
//     len(mockedInterface.GetCollectionByNameCalls())
func (mock *InterfaceMock) GetCollectionByNameCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	lockInterfaceMockGetCollectionByName.RLock()
	calls = mock.calls.GetCollectionByName
	lockInterfaceMockGetCollectionByName.RUnlock()
	return calls
}

// MethodGet calls MethodGetFunc.
func (mock *InterfaceMock) MethodGet(uri string, queryParams map[string]string, decodedResponse interface{}) error {
	if mock.MethodGetFunc == nil {
		panic("InterfaceMock.MethodGetFunc: method is nil but Interface.MethodGet was just called")
	}
	callInfo := struct {
		URI             string
		QueryParams     map[string]string
		DecodedResponse interface{}
	}{
		URI:             uri,
		QueryParams:     queryParams,
		DecodedResponse: decodedResponse,
	}
	lockInterfaceMockMethodGet.Lock()
	mock.calls.MethodGet = append(mock.calls.MethodGet, callInfo)
	lockInterfaceMockMethodGet.Unlock()
	return mock.MethodGetFunc(uri, queryParams, decodedResponse)
}

// MethodGetCalls gets all the calls that were made to MethodGet.
// Check the length with:
//     len(mockedInterface.MethodGetCalls())
func (mock *InterfaceMock) MethodGetCalls() []struct {
	URI             string
	QueryParams     map[string]string
	DecodedResponse interface{}
} {
	var calls []struct {
		URI             string
		QueryParams     map[string]string
		DecodedResponse interface{}
	}
	lockInterfaceMockMethodGet.RLock()
	calls = mock.calls.MethodGet
	lockInterfaceMockMethodGet.RUnlock()
	return calls
}
